### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by littlehifive** [nyuglobalties/panelcleaner#2]
1. The outer brackets are not necessary in the README instructions.

```r
(test_panel <- enpanel("test_panel", wave1, wave2))
```

2. `rlang` needs to be up-to-date to run `enpanel` :

```r
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.4.5 is already loaded, but >= 0.4.6 is required
```

3. Where can I find `panel_map_csv`?

**Comment by psanker** [comment]
1. The parens tell R to print the assigned value. `<-` _invisibly_ returns a value, which means printed output (when executed in the top level i.e. global environment) is suppressed. However, `(` does not suppress printing of values at top level. I used that trick as a shortcut to not have to write a second `test_panel` reference, but it's probably not worth the possible confusion.
1. Thanks for catching that!
1. `panel_map_csv` is a stand-in for a `data.frame` that was read in by `read.csv` or `read_csv`. I should clarify that.
